# Generated by Django 4.2.2 on 2023-06-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="название проекта"),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="project_photos/", verbose_name="фото проекта"
                    ),
                ),
                ("description", models.TextField(verbose_name="описание проета")),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False, verbose_name="отображение на сайте или нет"
                    ),
                ),
            ],
            options={
                "verbose_name": "проект",
                "verbose_name_plural": "проекты",
            },
        ),
        migrations.CreateModel(
            name="UserAppeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="имя клиента")),
                ("mail", models.EmailField(max_length=254, verbose_name="почта")),
                ("message", models.TextField(verbose_name="заявка")),
                (
                    "date",
                    models.DateField(auto_now_add=True, verbose_name="Дата заявки"),
                ),
            ],
            options={
                "verbose_name": "заявка",
                "verbose_name_plural": "заявки",
            },
        ),
    ]
